version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27018:27018
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password